### ISSUE TITLE
when try payment with "Pay later with Klarna." using Drop-in method produce PHP Fatal error: Uncaught Adyen\AdyenException: ReflectiveOperationException java.util.List

### ISSUE THREAD

**Issue by demonarola** [Adyen/adyen-php-api-library#145]
**PHP version**: 7.2
**Library version**: 5.0
**Description**

When i try to make payment using "Pay later with Klarna" using `/payment` function then got error like,

Fatal error: Uncaught Adyen\AdyenException: ReflectiveOperationException java.util.List in C:\wamp64\www\*******\vendor\adyen\php-api-library\src\Adyen\HttpClient\CurlClient.php on line 279

Is anyone got solution for this error?

**Comment by cyattilakiss** [comment]
Hi @demonarola ,

In that line indeed we throw an exception that you need to catch when you do the payments call.
In the exception you will have all the necessary and available information for the payment - why did it fail, what is the status and what is the psp reference if it does have any.

```
throw new AdyenException(
                $decodeResult['message'],
                $decodeResult['errorCode'],
                null,
                $decodeResult['status'],
                $decodeResult['errorType'],
                isset($decodeResult['pspReference']) ? $decodeResult['pspReference'] : null
            );
```

If you have an error message, most of the time the request object is not correct - maybe some required fields are missing or some values are not correct - and you need to figure out from the error message what is the issue. If you don't see any problem with your request object and the error message doesn't help because it's too generic or just says error, then I would suggest you to send an email to our tech support team at: support@adyen.com email address, attaching them this github ticket link, the request JSON that you send to the endpoint and the exception details that you catch.

I will close this ticket for now, but please feel free to reopen it if any library related issue shows up during the investigation with tech support.

Best regards and Happy New Year!
Attila
Adyen
