### ISSUE TITLE
PHP SDK Making payment Status: 500 Error

### ISSUE THREAD

**Issue by personGit2693** [Adyen/adyen-php-api-library#262]
Hi~ I tried to redirect the shopper at my payment method type, but unfortunately I got an error.
{"status":500,"errorCode":"701","message":"server could not process request","errorType":"internal","pspReference":"881615392704097H"}

I read another post here with same as my issue, adyen team did something on their end, they configured something to the account and after that the issue was solved, so I'm trying my chance if that would be also the solution for my issue.

**Comment by cyattilakiss** [comment]
Hi @personGit2693 ,

Thank you for raising this issue. Could you please reach out to our [support](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) team with the same details? Seems like indeed a configuration issue on your merchant account.

I will close this issue for now since this problem is not related to the library itself but the merchant account.

Best,
Attila
Adyen
