### ISSUE TITLE
 FRAUD-CANCELLED

### ISSUE THREAD

**Issue by sanjaykumar2338** [Adyen/adyen-php-api-library#268]
Array
(
    [pspReference] => 862618292500239A
    [refusalReason] => FRAUD-CANCELLED
    [resultCode] => Cancelled
    [refusalReasonCode] => 22
    [merchantReference] => 60752f115d9ab
)

what is the reason behind it?

**Comment by cyattilakiss** [comment]
Hi @sanjaykumar2338 ,

This is a cancellation result triggered by your Fraud rules: https://docs.adyen.com/development-resources/refusal-reasons
About risk management (including risk rules) you can read more here: https://docs.adyen.com/risk-management
In case you still have some questions please search in our documentation or reach out to support via the link you can find in  this repository's Readme file.

I hope this helps!
I will close this issue for now because this is not a library specific topic.

Best,
Attila
Adyen

**Comment by sanjaykumar2338** [comment]
@cyattilakiss Thanks for your reply.
But I have created a test account for transactions, then why throwing this error?

**Comment by cyattilakiss** [comment]
Hi @sanjaykumar2338 ,

There are some default risk rules that might be triggered even for a new test account. Please check your risk settings in your customer area. In case you cannot find the reason please reach out to support they will be happy to help and also answering quite fast.

Best,
Attila
Adyen

**Comment by sanjaykumar2338** [comment]
Thank you @cyattilakiss
