### ISSUE TITLE
Mixed use of quotes

### ISSUE THREAD

**Issue by szepeviktor** [Adyen/adyen-php-api-library#281]
**Is your feature request related to a problem? Please describe.**
Clean code uses only single quotes.

**Describe the solution you'd like**
I'd send a PR with changing all quotes to single quotes.

Will you merge it?

**Comment by szepeviktor** [comment]
PHPCS understands `<rule ref="Squiz.Strings.DoubleQuoteUsage.NotRequired"/>`

**Comment by acampos1916** [comment]
@szepeviktor sure, you can create the PR.

**Comment by szepeviktor** [comment]
@jillingk I am very sad that a company like Adyen does not a follow a (any) coding standard.
What do you think about it?

**Comment by jillingk** [comment]
Hi @szepeviktor,

First of all thanks for all the contributions and suggestions you have made, it's definitely much appreciated. 

Since your last PR, we have internally aligned our coding standard a bit. However, I agree with you that this could use improvement and should also be more transparant! I will discuss this with the team as well and let you know the outcome. 

Have a nice day!

Best, Jilling
Adyen

**Comment by szepeviktor** [comment]
I was wrong. You follow PSR-2.
But it does not include rules for quotes.
