### ISSUE TITLE
TermUrl missing from action attribute on payment response

### ISSUE THREAD

**Issue by fernandocoronatomf** [Adyen/adyen-php-api-library#407]
**Describe the bug**
After upgrading to V13.0.0, the response for 3DS payments action attribute does not contain "data.TermUrl".

**To Reproduce**
Checkout API V68
`
array:2 [
  "resultCode" => "RedirectShopper"
  "action" => array:5 [
    "paymentMethodType" => "scheme"
    "url" => "https://checkoutshopper-test.adyen.com/checkoutshopper/threeDS2.shtml?pspReference=ZZZZ"
    "data" => array:3 [
      "MD" => "Redacted"
      "PaReq" => "Redacted"
      "TermUrl" => "https://checkoutshopper-test.adyen.com/checkoutshopper/threeDS/return/redacted"
    ]
    "method" => "POST"
    "type" => "redirect"
  ]
]`

Checkout API V68

`array:2 [
  "resultCode" => "RedirectShopper"
  "action" => array:5 [
    "paymentMethodType" => "scheme"
    "url" => "https://checkoutshopper-test.adyen.com/checkoutshopper/threeDS/checkoutRedirect/"
    "data" => array:2 [
      "MD" => "redacted"
      "PaReq" => "redacted"
    ]
    "method" => "POST"
    "type" => "redirect"
  ]
]`

Has this change been discussed in the change log from V68 to V69?
I am looking for a change log on your docs but can't find it.  

![image](https://user-images.githubusercontent.com/1309374/190350054-35d28628-c008-48ba-ab9d-b215f88e694f.png)

**Comment by jillingk** [comment]
Hi @fernandocoronatomf,

Thank you for reaching out to us, It seems that this is not really a library sided issue but more on the functionality change in the Checkout API. I've seen this issue get asked more though, so let me quickly run you through the change. From v69 you will not get a ```TermUrl``` anymore in the gluepages flow, just the ```PaReq``` and ```MD```. You're supposed to post this to the ```url```. This would forward the shopper to the corresponding issuer. That's pretty much all!

Hope this helps, if not I would recommend reaching out to support since this is really not our expertise and they will definitely be able to help you along further. I will however reach out to you with our checkout team so that hopefully in the future we get some more descriptive release notes :)

Best, Jilling
Adyen
