### ISSUE TITLE
API response not correctly handled

### ISSUE THREAD

**Issue by thedigital** [Adyen/adyen-php-api-library#490]
**Describe the bug**
From branch https://github.com/Adyen/adyen-php-api-library/pull/489
When trying to update Apple Pay domains, it always gives this error : Probably your Web Service username and/or password is incorrect
(Network error [errno 0]: )  
But it did work as you can see in Adyen api logs : https://ca-test.adyen.com/ca/ca/api/logdetails.shtml?logID=APIL4224Q22322595HPHJR2BJ25458

**To Reproduce**
1. Use code from the pull request : https://github.com/Adyen/adyen-php-api-library/pull/489
2. Call $service->merchantAccount->addApplePayDomains($merchantId, $paymentMethodId, ['domains' => [...]'])
3. See error in response after call
4. See "accepted" response in Adyen api logs 

**Expected behavior**
Succesful response

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jillingk** [comment]
Hi @thedigital,

Thanks for reaching out to us and making the contributions! It's highly appreciated. The issue you're seeing will actually be fixed by #464 (basically the client would always throw an error for an empty response body, even though you would expect that in for example DELETE request or in this case the POST with empty response body). 

Best, Jilling
Adyen

**Comment by thedigital** [comment]
Hi Jilling

Ok thank you for your answer ! Nothing to add :)

Good day
